### ISSUE TITLE
Cannot run Caffe2 model with profiling

### ISSUE THREAD

**Issue by mneilly-et** [facebookresearch/dlrm#109]
I was trying to run the Caffe2 version of DLRM with --enable-profiling. It appears that the log_dir and caffe2_logging_print_net_summary options being used by DLRM are no longer valid.

[https://github.com/facebookresearch/dlrm/blob/21d00785a3b964973e5642ead112b55492157372/dlrm_s_caffe2.py#L491-L497](https://github.com/facebookresearch/dlrm/blob/21d00785a3b964973e5642ead112b55492157372/dlrm_s_caffe2.py#L491-L497
)

PyTorch version is as follows:
```
$ pip list | grep -i torch
torch                  1.7.0a0+2cf31fb
```

The errors are:
```
C10 flag: unrecognized commandline argument: --log_dir=$HOME
C10 flag: unrecognized commandline argument: --caffe2_logging_print_net_summary=1
```

The full output is as follows:
```
$ (export OMP_NUM_THREADS=1 && numactl --physcpubind=0 -m 0,1 python ./dlrm_s_caffe2.py --mini-batch-size 1 --arch-sparse-feature-size 32 --arch-embedding-size 1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000 --num-indices-per-lookup 10 --num-batches 10 --data-generation random --arch-mlp-bot 2560-512-32 --arch-mlp-top 1024-512-256-1 --num-indices-per-lookup-fixed True --arch-interaction-op dot --numpy-rand-seed $RANDOM --print-freq 1 --print-time --inference-only --enable-profiling)
Using CPU...
Parsing commandline arguments for c10.
C10 flag: unrecognized commandline argument: --caffe2_logging_print_net_summary=1
Traceback (most recent call last):
  File "./dlrm_s_caffe2.py", line 964, in <module>
    enable_prof=args.enable_profiling,
  File "./dlrm_s_caffe2.py", line 487, in __init__
    workspace.GlobalInit(global_init_opt)
RuntimeError: [enforce fail at init.cc:89] success. Failed to run some init functions for caffe2.
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x47 (0x7f13d9f24fd7 in /eng/mneilly/.virtualenvs/dlrm/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: caffe2::GlobalInit(int*, char***) + 0x532 (0x7f13ef03fae2 in /eng/mneilly/.virtualenvs/dlrm/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch_cpu.so)
frame #2: <unknown function> + 0x13119f (0x7f13f457119f in /eng/mneilly/.virtualenvs/dlrm/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x175a73 (0x7f13f45b5a73 in /eng/mneilly/.virtualenvs/dlrm/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #25: __libc_start_main + 0xf5 (0x7f14085483d5 in /lib64/libc.so.6)
frame #26: python() [0x400c20]

```

**Comment by mnaumovfb** [comment]
We can reproduce this error. Can you please try commenting out these lines and running the code again?
```
# "--log_dir=$HOME", 
# "--caffe2_logging_print_net_summary=1",
```

Let us know if it works for you.

**Comment by mneilly-et** [comment]
Thanks @mnaumovfb, yes, commenting the lines out allows things to run. I guess if there is no replacement for the options then we will pursue another route. Thanks for taking a look.

**Comment by mneilly-et** [comment]
To follow up, it looks like the missing options are a red herring for what I'm really after which is running a C2 profiler that will give a per operator breakdown. 

I made the following changes:
```
diff --git a/dlrm_s_caffe2.py b/dlrm_s_caffe2.py
index 47b27d6..6e4c808 100644
--- a/dlrm_s_caffe2.py
+++ b/dlrm_s_caffe2.py
@@ -490,8 +490,8 @@ class DLRM_Net(object):
             if enable_prof:
                 global_init_opt += [
                     "--logtostderr=0",
-                    "--log_dir=$HOME",
-                    "--caffe2_logging_print_net_summary=1",
+                    #"--log_dir=$HOME",
+                    #"--caffe2_logging_print_net_summary=1",
                 ]
             workspace.GlobalInit(global_init_opt)
             self.set_tags()
@@ -1122,7 +1122,7 @@ if __name__ == "__main__":
             # forward and backward pass, where the latter runs only
             # when gradients and loss have been added to the net
             time1 = time.time()
-            dlrm.run(lX[j], lS_l[j], lS_i[j], lT[j])  # args.enable_profiling
+            dlrm.run(lX[j], lS_l[j], lS_i[j], lT[j], enable_prof=args.enable_profiling)
             time2 = time.time()
             total_time += time2 - time1
```

Which cause the existing conditional code that calls workspace.C.benchmark_net(...) to run but unfortunately it looks like that option doesn't work with DLRM_Net. 

```
[I net.cc:207] Starting benchmark, running warmup runs
[I net.cc:216] Running main runs
[I net.cc:227] Main runs finished. Milliseconds per iter: 0.179075. Iters per second: 5584.25
**[I net.cc:232] Net does not support per-op benchmark; to run it, switch to a simple net type**
Finished inference it 10/10 of epoch 0, 0.50 ms/it, loss 0.000000, accuracy 0.000 %
```

**Comment by mnaumovfb** [comment]
Unfortunately, I don't think this is supported in Caffe2 anymore. I would ask about it on Caffe2/PyTorch forums.
