### ISSUE TITLE
RuntimeError while export pytorch model into onnx

### ISSUE THREAD

**Issue by deepeshguru** [facebookresearch/dlrm#124]
# Unable to export model into onnx.
## Getting error while running this command "python dlrm_s_pytorch.py --save-onnx":

Using CPU...
time/loss/accuracy (if enabled):
Finished training it 1/1 of epoch 0, -1.00 ms/it, loss 0.083850, accuracy 0.000 %
dlrm_s_pytorch.py:317: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  li = torch.tensor([i for i in range(ni) for j in range(i + offset)])
dlrm_s_pytorch.py:317: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  li = torch.tensor([i for i in range(ni) for j in range(i + offset)])
dlrm_s_pytorch.py:318: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  lj = torch.tensor([j for i in range(nj) for j in range(i + offset)])
dlrm_s_pytorch.py:318: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  lj = torch.tensor([j for i in range(nj) for j in range(i + offset)])
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 1267, in <module>
    dlrm, (X_onnx, lS_o_onnx, lS_i_onnx), dlrm_pytorch_onnx_file, verbose=True, use_external_data_format=True, opset_version=10
  File "/home/amd/anaconda3/envs/mkl_pytorchc1.6/lib/python3.7/site-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/amd/anaconda3/envs/mkl_pytorchc1.6/lib/python3.7/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/home/amd/anaconda3/envs/mkl_pytorchc1.6/lib/python3.7/site-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/amd/anaconda3/envs/mkl_pytorchc1.6/lib/python3.7/site-packages/torch/onnx/utils.py", line 384, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/home/amd/anaconda3/envs/mkl_pytorchc1.6/lib/python3.7/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/amd/anaconda3/envs/mkl_pytorchc1.6/lib/python3.7/site-packages/torch/onnx/__init__.py", line 241, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/amd/anaconda3/envs/mkl_pytorchc1.6/lib/python3.7/site-packages/torch/onnx/utils.py", line 791, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/amd/anaconda3/envs/mkl_pytorchc1.6/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 129, in wrapper
    return fn(g, *args)
  File "/home/amd/anaconda3/envs/mkl_pytorchc1.6/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py", line 413, in embedding_bag
    return sym_help._onnx_unsupported('embedding_bag')
  File "/home/amd/anaconda3/envs/mkl_pytorchc1.6/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 181, in _onnx_unsupported
    'Please open a bug to request ONNX export support for the missing operator.'.format(op_name))
RuntimeError: Unsupported: ONNX export of operator embedding_bag. Please open a bug to request ONNX export support for the missing operator.

**Comment by mnaumovfb** [comment]
Please make sure that you have installed the latest nightly pytorch and onnx versions and then re-try with the latest dlrm.

**Comment by deepeshguru** [comment]
Thanks @mnaumovfb , By using nightly pytorch it works, but size of onnx file is very small (5.91 KB). Is size of onnx is fine or something wrong.

**Comment by mnaumovfb** [comment]
The model is broken into multiple files, the onnx file you are looking at is probably the one that just assembles them together (notice that most of the weights, beyond some threshold per layer, are stored in separate files).

**Comment by deepeshguru** [comment]
Thanks again @mnaumovfb
