### ISSUE TITLE
Dataloader fails when num-workers > 1 for criteo datasets

### ISSUE THREAD

**Issue by lkp411** [facebookresearch/dlrm#159]
Hello there,

When I use num-workers > 1, I get the following error with the Criteo terabyte dataset. Including a full stack trace.

The command line I use is:

python3 dlrm_s_pytorch.py --arch-sparse-feature-size=64 --arch-mlp-bot="13-512-256-64" --arch-mlp-top="512-512-256-1" --max-ind-range=100000000 --data-generation=dataset --data-set=terabyte --raw-data-file=/ssd/ssd1/keshav/dlrm/data/terabyte/day --processed-data-file=/ssd/ssd1/keshav/dlrm/data/terabyte/terabyte_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=4096 --print-freq=1024 --print-time --test-mini-batch-size=2048 --test-num-workers=16 --test-freq=8192 --memory-map --data-sub-sample-rate=0.875 --use-gpu --num-workers=2

The error is:

Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 1869, in <module>
    run()
  File "dlrm_s_pytorch.py", line 1508, in run
    for j, inputBatch in enumerate(train_ld):
  File "/home/keshavba/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/keshavba/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1065, in _next_data
    return self._process_data(data)
  File "/home/keshavba/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/keshavba/.local/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/keshavba/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/keshavba/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/keshavba/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/keshavba/research/projects/Dlrm/dlrm/dlrm_data_pytorch.py", line 288, in __getitem__
    i = index - self.day_boundary
AttributeError: 'CriteoDataset' object has no attribute 'day_boundary'

**Comment by mnaumovfb** [comment]
You can not mix --num-workers and --test-num-workers with --memory-map flag. You can only use the former two or the latter.
