### ISSUE TITLE
Terabyte Dataset: Issue inferencing with embedding quantization

### ISSUE THREAD

**Issue by latifisalar** [facebookresearch/dlrm#166]
Hi there,

I have been having issues running the inference on CPU for the trained dlrm model with the quantized embeddings.

Here is the command that I am running:
`./bench/dlrm_s_criteo_terabyte.sh "--test-freq=10240 --memory-map --data-sub-sample-rate=0.875 --raw-data-file=/data4/salar/terabyte/day --inference-only --load-model=Baseline_trained.pt --mlperf-logging --quantize-emb-with-bit=8"`

I have tried running it with two different PyTorch versions and I have failed in both of them with different errors:

**torch==1.9.0.dev20210305:**
`Testing for inference only
quantized emb sizes: 718583976 718583976
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 1879, in <module>
    run()
  File "dlrm_s_pytorch.py", line 1762, in run
    use_gpu,
  File "dlrm_s_pytorch.py", line 791, in inference
    ndevices=ndevices,
  File "dlrm_s_pytorch.py", line 138, in dlrm_wrap
    return dlrm(X.to(device), lS_o, lS_i)
  File "/home/salar/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1015, in _call_impl
    return forward_call(*input, **kwargs)
  File "dlrm_s_pytorch.py", line 517, in forward
    return self.sequential_forward(dense_x, lS_o, lS_i)
  File "dlrm_s_pytorch.py", line 589, in sequential_forward
    ly = self.apply_emb(lS_o, lS_i, self.emb_l, self.v_W_l)
  File "dlrm_s_pytorch.py", line 439, in apply_emb
    per_sample_weights=per_sample_weights,
RuntimeError: Expect weight, indices, and offsets to be contiguous.`

**torch==1.7.1+cu110:**
`Testing for inference only
quantized emb sizes: 718583976 718583976
quantized emb sizes: 2598048 2598048
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 1878, in <module>
    run()
  File "dlrm_s_pytorch.py", line 1761, in run
    use_gpu,
  File "dlrm_s_pytorch.py", line 791, in inference
    ndevices=ndevices,
  File "dlrm_s_pytorch.py", line 138, in dlrm_wrap
    return dlrm(X.to(device), lS_o, lS_i)
  File "/home/salar/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "dlrm_s_pytorch.py", line 517, in forward
    return self.sequential_forward(dense_x, lS_o, lS_i)
  File "dlrm_s_pytorch.py", line 589, in sequential_forward
    ly = self.apply_emb(lS_o, lS_i, self.emb_l, self.v_W_l)
  File "dlrm_s_pytorch.py", line 439, in apply_emb
    per_sample_weights=per_sample_weights,
RuntimeError: FBGEMM GenerateEmbeddingSpMDM kernel failed for 8-bit input`

I would really appreciate if someone could help me on how to properly apply embedding quantization.

Thanks!

**Comment by amirstar** [comment]
I tried to reproduce the error by training a model on Terabyte with this command: 
`./dlrm_s_criteo_terabyte.sh "--save-model=./test.pt --test-freq=10240 --memory-map --data-sub-sample-rate=0.875 --raw-data-file=./input/day --quantize-emb-with-bit=8 --num-batches=100"`

Then I used the saved model to test (inference-only) with this command : 
`./dlrm_s_criteo_terabyte.sh "--test-freq=10240 --memory-map --data-sub-sample-rate=0.875 --raw-data-file=./input/day --inference-only --load-model=./test.pt --quantize-emb-with-bit=8 --num-batches=200"`

The results are fine. I was not successful to reproduce the error. My torch is 1.7 CPU only. Could you please double check that the training and testing both run on CPU? or just try the above commands to see if they work?

**Comment by TigranI** [comment]
The quantization only works on CPU at this point. In the current version if quantization is attempted on GPU, code exits with an error message.
