### ISSUE TITLE
visualization is malfunction 

### ISSUE THREAD

**Issue by jeng1220** [facebookresearch/dlrm#21]
I followed the instructions to enable visualization:
```diff
-# from torchviz import make_dot
-# import torch.nn.functional as Functional
-# from torch.nn.parameter import Parameter
+from torchviz import make_dot
+import torch.nn.functional as Functional
+from torch.nn.parameter import Parameter
```
and 
```diff
     # plot compute graph
     if args.plot_compute_graph:
-        sys.exit(
-            "ERROR: Please install pytorchviz package in order to use the"
-            + " visualization. Then, uncomment its import above as well as"
-            + " three lines below and run the code again."
-        )
-        # V = Z.mean() if args.inference_only else L
-        # make_dot(V, params=dict(dlrm.named_parameters()))
-        # dot.render('dlrm_s_pytorch_graph') # write .pdf file
+        V = Z.mean() if args.inference_only else L
+        make_dot(V, params=dict(dlrm.named_parameters()))
+        dot.render('dlrm_s_pytorch_graph') # write .pdf file
```
then ran the command:
```bash
$ python ./dlrm_s_pytorch.py  --plot-compute-graph
```
However, I encountered error:
```bash
Traceback (most recent call last):
  File "./dlrm_s_pytorch.py", line 891, in <module>
    make_dot(V, params=dict(dlrm.named_parameters()))
  File "/opt/conda/lib/python3.6/site-packages/torchviz/dot.py", line 37, in make_dot
    output_nodes = (var.grad_fn,) if not isinstance(var, tuple) else tuple(v.grad_fn for v in var)
AttributeError: 'numpy.ndarray' object has no attribute 'grad_fn'
```
Could anyone help please?

Environment:
* ubuntu 18.04
* python 3.6.8
* torch 1.2.0a0+0885dd2
* torchtext 0.4.0          
* torchvision 0.2.1          
* torchviz 0.0.1 
* graphviz 0.11.1

**Comment by mnaumovfb** [comment]
Thank you for pointing out this issue. We have updated the code with a working version.

The fix is to use "E" instead of "L" on the following and define "dot" on the subsequent line:
# V = Z.mean() if args.inference_only else E                                                                                                           
# dot = make_dot(V, params=dict(dlrm.named_parameters()))

**Comment by jeng1220** [comment]
Thanks for reply. It works and close this issue.
