### ISSUE TITLE
Error running training with the bin dataset

### ISSUE THREAD

**Issue by rakshithvasudev** [facebookresearch/dlrm#247]
Hello There,

I'm trying to run training with the terabyte mlperf bin dataset. I'm seeing this error. 

```
root@3a2e1d68414f:/workspace/dlrm# python dlrm_s_pytorch.py --arch-embedding-size=128 --arch-sparse-feature-size=26 --arch-mlp-bot="512-256-128-26" --arch-mlp-top="1024-1024-512-256-1" --data-generation=dataset --num-batches=5 --use-gpu  --processed-data-file=/dataset/ --memory-map  --mlperf-bin-loader --data-set=terabyte
world size: 1, current rank: 0, local rank: 0
Using 8 GPU(s)...
data file: /dataset/train_data.bin number of batches: 4195197692
data file: /dataset/test_data.bin number of batches: 89137319
time/loss/accuracy (if enabled):
/workspace/dlrm/data_loader_terabyte.py:231: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable
before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:172.)
  tensor = torch.from_numpy(array).view((-1, self.tot_fea))
Finished training it 1/5 of epoch 0, -1.00 ms/it, loss 0.168854
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [0,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [1,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [2,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [3,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [4,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [5,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [6,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [7,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [8,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [9,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [10,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [11,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [12,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [13,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [14,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [15,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [16,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [17,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [18,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [19,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [20,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [21,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [22,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [23,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [24,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [25,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 1877, in <module>
    run()
  File "dlrm_s_pytorch.py", line 1551, in run
    Z = dlrm_wrap(
  File "dlrm_s_pytorch.py", line 136, in dlrm_wrap
    return dlrm(X.to(device), lS_o, lS_i)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "dlrm_s_pytorch.py", line 514, in forward
    return self.sequential_forward(dense_x, lS_o, lS_i)
  File "dlrm_s_pytorch.py", line 591, in sequential_forward
    z = self.interact_features(x, ly)
  File "dlrm_s_pytorch.py", line 493, in interact_features
    Zflat = Z[:, li, lj]
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
Any help would be appreciated to fix/debug this.

Here's the command I'm running:

`python dlrm_s_pytorch.py --arch-embedding-size=128 --arch-sparse-feature-size=26 --arch-mlp-bot="512-256-128-26" --arch-mlp-top="1024-1024-512-256-1" --data-generation=dataset --num-batches=5 --use-gpu  --processed-data-file=/dataset/ --memory-map  --mlperf-bin-loader --mlperf-logging --data-set=terabyte`

**Comment by rakshithvasudev** [comment]
Here is the error after running `export CUDA_LAUNCH_BLOCKING=1
`
```
/workspace/dlrm/data_loader_terabyte.py:231: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:172.)
  tensor = torch.from_numpy(array).view((-1, self.tot_fea))
Finished training it 1/5 of epoch 0, -1.00 ms/it, loss 0.168854
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [0,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [1,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [2,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [3,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [4,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [5,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [6,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [7,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [8,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [9,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [10,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [11,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [12,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [13,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [14,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [15,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [16,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [17,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [18,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [19,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [20,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [21,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [22,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [23,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [24,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/EmbeddingBag.cu:128: EmbeddingBag_updateOutputKernel_sum_mean: block: [0,0,0], thread: [25,0,0] Assertion `input[emb] >= 0 && input[emb] < vocab_size` failed.
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 1877, in <module>
    run()
  File "dlrm_s_pytorch.py", line 1551, in run
    Z = dlrm_wrap(
  File "dlrm_s_pytorch.py", line 136, in dlrm_wrap
    return dlrm(X.to(device), lS_o, lS_i)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "dlrm_s_pytorch.py", line 514, in forward
    return self.sequential_forward(dense_x, lS_o, lS_i)
  File "dlrm_s_pytorch.py", line 586, in sequential_forward
    ly = self.apply_emb(lS_o, lS_i, self.emb_l, self.v_W_l)
  File "dlrm_s_pytorch.py", line 442, in apply_emb
    V = E(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 383, in forward
    return F.embedding_bag(input, self.weight, offsets,
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2329, in embedding_bag
    ret, _, _, _ = torch.embedding_bag(
RuntimeError: CUDA error: device-side assert triggered
 
```

**Comment by mnaumovfb** [comment]
Can you try the following command and let me know if it works?
https://github.com/facebookresearch/dlrm/blob/main/bench/run_and_time.sh#L17
