### ISSUE TITLE
jagged_2d_to_dense Error

### ISSUE THREAD

**Issue by nippleshot** [facebookresearch/dlrm#285]
Hi, I'm just tryin to run `torchrec_dlrm` and i'm stuck with jagged_2d_to_dense error
I tried both stable and nightly version of torchrec (and matched fbgemm-gpu version also) 

**Stable version** : (docker image : nvcr.io/nvidia/pytorch:22.04-py3)
```c
fbgemm-gpu                0.3.0                    pypi_0    pypi
python                    3.8.13          h582c2e5_0_cpython    conda-forge
torch                     1.12.0a0+bd13bc6         pypi_0    pypi
torchrec                  0.3.1                    pypi_0    pypi
torchx-nightly            2022.11.7                pypi_0    pypi
```
and when i run `torchx run -s local_cwd dist.ddp -j 1x8 --script dlrm_main.py` this is my error for stable version :
```c
...
dlrm_main/0 [0]:libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory
dlrm_main/0 [0]:Traceback (most recent call last):
dlrm_main/0 [0]:  File "dlrm_main.py", line 18, in <module>
dlrm_main/0 [0]:    from fbgemm_gpu.split_embedding_configs import EmbOptimType as OptimType
dlrm_main/0 [0]:  File "/opt/conda/lib/python3.8/site-packages/fbgemm_gpu/__init__.py", line 22, in <module>
dlrm_main/0 [0]:    from . import _fbgemm_gpu_docs
dlrm_main/0 [0]:  File "/opt/conda/lib/python3.8/site-packages/fbgemm_gpu/_fbgemm_gpu_docs.py", line 18, in <module>
dlrm_main/0 [0]:    torch.ops.fbgemm.jagged_2d_to_dense,
dlrm_main/0 [0]:  File "/opt/conda/lib/python3.8/site-packages/torch/_ops.py", line 191, in __getattr__
dlrm_main/0 [0]:    op = torch._C._jit_get_operation(qualified_op_name)
dlrm_main/0 [0]:RuntimeError: No such operator fbgemm::jagged_2d_to_dense
...
```
---

**Nightly version** : (docker image : nvcr.io/nvidia/pytorch:22.07-py3)
```c
fbgemm-gpu-nightly        2022.11.7                pypi_0    pypi
python                    3.8.13          h582c2e5_0_cpython    conda-forge
torch                     1.13.0a0+d321be6         pypi_0    pypi
torchrec-nightly          2022.11.7                pypi_0    pypi
torchx-nightly            2022.11.7                pypi_0    pypi
```
and when i run `torchx run -s local_cwd dist.ddp -j 1x8 --script dlrm_main.py` this is my error for nightly version :
```c
...
dlrm_main/0 [0]:/opt/conda/lib/python3.8/site-packages/fbgemm_gpu/fbgemm_gpu_py.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv
dlrm_main/0 [0]:Traceback (most recent call last):
dlrm_main/0 [0]:  File "/opt/conda/lib/python3.8/site-packages/torch/_ops.py", line 203, in __getattr__
dlrm_main/0 [0]:    op, overload_names = torch._C._jit_get_operation(qualified_op_name)
dlrm_main/0 [0]:RuntimeError: No such operator fbgemm::jagged_2d_to_dense
dlrm_main/0 [0]:
dlrm_main/0 [0]:The above exception was the direct cause of the following exception:
dlrm_main/0 [0]:
dlrm_main/0 [0]:Traceback (most recent call last):
dlrm_main/0 [0]:  File "dlrm_main.py", line 18, in <module>
dlrm_main/0 [0]:    from fbgemm_gpu.split_embedding_configs import EmbOptimType as OptimType
dlrm_main/0 [0]:  File "/opt/conda/lib/python3.8/site-packages/fbgemm_gpu/__init__.py", line 21, in <module>
dlrm_main/0 [0]:    from . import _fbgemm_gpu_docs  # noqa: F401, E402
dlrm_main/0 [0]:  File "/opt/conda/lib/python3.8/site-packages/fbgemm_gpu/_fbgemm_gpu_docs.py", line 18, in <module>
dlrm_main/0 [0]:    torch.ops.fbgemm.jagged_2d_to_dense,
dlrm_main/0 [0]:  File "/opt/conda/lib/python3.8/site-packages/torch/_ops.py", line 207, in __getattr__
dlrm_main/0 [0]:    raise AttributeError(f"'_OpNamespace' object has no attribute '{op_name}'") from e
dlrm_main/0 [0]:AttributeError: '_OpNamespace' object has no attribute 'jagged_2d_to_dense'
...
```

**Comment by samiwilf** [comment]
torch  1.13.0a0+d321be6 isn't nightly any more.  pip uninstall torch and install pytorch nightly using an install command from https://pytorch.org/get-started/locally/

**Comment by nippleshot** [comment]
After I installed pytorch-nightly, torchrec-nightly(+fbgemm-gpu-nightly) with pip it works! 
(conda install/uninstall still doesn't work for me)
