### ISSUE TITLE
dlrm terabyte training crashes when running on test data set

### ISSUE THREAD

**Issue by rohithkrn** [facebookresearch/dlrm#47]
Using the below command from `./bench/dlrm_s_criteo_terabyte.sh`
```
python3.6 dlrm_s_pytorch.py --arch-sparse-feature-size=64 --arch-mlp-bot="13-512-256-64" --arch-mlp-top="512-512-256-1" --max-ind-range=10000000 --data-generation=dataset --data-set=terabyte --raw-data-file=/rafa/terabyte/day --processed-data-file=/rafa/terabyte/terabyte_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=2048 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --use-gpu --data-sub-sample-rate=0.875 --memory-map --test-freq 1024
```

The command crashes with the error below:
```
Using 1 GPU(s)...
Reading pre-processed data=/rafa/terabyte/terabyte_processed.npz
Sparse features= 26, Dense features= 13
Reading pre-processed data=/rafa/terabyte/terabyte_processed.npz
Sparse features= 26, Dense features= 13
time/loss/accuracy (if enabled):
Finished training it 1024/315310 of epoch 0, 97.42 ms/it, loss 0.476448, accuracy 78.929 %
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 866, in <module>
    for jt, (X_test, lS_o_test, lS_i_test, T_test) in enumerate(test_loader):
  File "/root/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 801, in __next__
    return self._process_data(data)
  File "/root/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/root/.local/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/rafa/dlrm/dlrm_data_pytorch.py", line 286, in __getitem__
    return self.X_int[i], self.X_cat[i], self.y[i]
AttributeError: 'CriteoDataset' object has no attribute 'X_int'
```

I could work around this by setting`--test-num-workers=0` and the training runs to completion.

@mnaumovfb

**Comment by mustafaozdal** [comment]
Can you please change "--test-num-workers=16" to "--test-num-workers=0" in the command line for now? There's an issue with multiple workers in --memory-map mode, which we will fix in a few days. This workaround should be sufficient for now.

**Comment by rohithkrn** [comment]
Thanks for your response. As mentioned in my previous comment, I have already set `--test-num-workers=0` and ran the the training.

**Comment by mustafaozdal** [comment]
Sorry about missing your previous comment. We just pushed a fix for this issue. Can you please try again when you have a chance? Thanks.

**Comment by rohithkrn** [comment]
@mustafaozdal Tried with fix and it doesn't crash. Thanks.
