### ISSUE TITLE
plot_compute_graph

### ISSUE THREAD

**Issue by ConnollyLeon** [facebookresearch/dlrm#71]
I'm trying to use the torchviz to generize a compute graph, but fail to do it.
A runtime error happens when using make_dot.
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 962, in <module>
    dot = make_dot(V, params=dict(dlrm.named_parameters()))
  File "/anaconda3/lib/python3.6/site-packages/torchviz-0.0.1-py3.6.egg/torchviz/dot.py", line 70, in make_dot
  File "/anaconda3/lib/python3.6/site-packages/torchviz-0.0.1-py3.6.egg/torchviz/dot.py", line 59, in add_nodes
  File "/anaconda3/lib/python3.6/site-packages/torchviz-0.0.1-py3.6.egg/torchviz/dot.py", line 59, in add_nodes
  File "/anaconda3/lib/python3.6/site-packages/torchviz-0.0.1-py3.6.egg/torchviz/dot.py", line 59, in add nodes
 File "/anaconda3/lib/python3.6/site-packages/torchviz-0.0.1-py3.6.egg/torchviz/dot.py", line 60, in add_nodes
RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

**Comment by mnaumovfb** [comment]
Please try doing the following. Change [line 929 in dlrm_s_pytorch.py](https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L929) 
E.backward(retain_graph=True)

Let me know if it helps. You'll find the corresponding doc [here](https://pytorch.org/docs/stable/autograd.html?highlight=backward#torch.Tensor.backward)

**Comment by ConnollyLeon** [comment]
It works! Thanks for your help.
I suggest that this ploting can be put before training and before some preprocessing. So that we don't have to generate this plot by setting parameters like num-batches to 1 and so on, if we want this ploting to be fast.

Closing issue.
