### ISSUE TITLE
Dataloader, ERROR: Unexpected Segmentation fault encountered in worker

### ISSUE THREAD

**Issue by YJYJLee** [facebookresearch/dlrm#80]
Hi, I'm trying to run criteo kaggle dataset with 16 cpus, and I have following error when training the model.
It randomly crashes  regardless of epoch number and I am using below command for training:
**$dlrm_pt_bin --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file="$data_path/train.txt" --processed-data-file="$data_path/kaggleAdDisplayChallenge_processed.npz" --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --save-model=testtest --test-freq=10 $dlrm_extra_option 2>&1 | tee run_kaggle_pt.log**

I think it started to crash after I added test-freq argument. 
I googled about this problem, and people said it's pytorch's problem and setting num-workers to zero resolves the problem. But it's default value is already set to zero, so I don't think it is the appropriate solution. 

Has anyone faced this problem while training the model?

Full trace:
-------------------------------------------------------------------------------------------------
Testing at - 950/306969 of epoch 0, loss 0.511735, accuracy 75.604 %, best 75.604 %
Finished training it 960/306969 of epoch 0, 25.53 ms/it, loss 0.500798, accuracy 76.797 %
Testing at - 960/306969 of epoch 0, loss 0.511752, accuracy 75.400 %, best 75.604 %
Finished training it 970/306969 of epoch 0, 22.57 ms/it, loss 0.487662, accuracy 77.109 %
Saving model to yejin
Testing at - 970/306969 of epoch 0, loss 0.510336, accuracy 75.676 %, best 75.676 %
Finished training it 980/306969 of epoch 0, 26.47 ms/it, loss 0.503259, accuracy 76.250 %
ERROR: Unexpected segmentation fault encountered in worker.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/reductions.py", line 294, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 1027, in <module>
    for i, (X_test, lS_o_test, lS_i_test, T_test) in enumerate(test_ld):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 808, in _get_data
    success, data = self._try_get_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 769, in _try_get_data
    if self._workers_status[worker_id] and not w.is_alive():
  File "/usr/lib/python3.6/multiprocessing/process.py", line 134, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 25377) is killed by signal: Segmentation fault.
done

**Comment by mnaumovfb** [comment]
I have not seen this problem. However, I would concur with the suggestion of setting both `--num-workers=0` and `--test-num-workers=0` and try running again. Note that in the command line above the former parameter has the default value of 0, but the latter parameter is set to 16.

**Comment by mnaumovfb** [comment]
There have been no comments in a while. I'm assuming this is resolved. Closing.
